apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: joplin-ingress-route
  namespace: joplin-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`joplin.winetree94.com`)
      kind: Rule
      services:
        - name: joplin-service
          port: 80
  tls:
    secretName: letsencrypt-cert
