apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - joplin.namespace.yaml
  - joplin.database.superuser.secret.yaml
  - joplin.database.user.secret.yaml
  - joplin.database.yaml
  - joplin.deployment.yaml
  - joplin.service.yaml
  - joplin.ingress-route.yaml
