apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external-release
  namespace: traefik-external-system
spec:
  chart:
    spec:
      chart: traefik
      version: "37.4.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: traefik-external
  values:
    ports:
      postgres:
        port: 5432
        expose: true
        exposedPort: 5432
        protocol: TCP
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
        ingressClass: "traefik-external"
      kubernetesIngress:
        allowExternalNameServices: true
        ingressClass: "traefik-external"
    deployment:
      replicas: 2
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: "traefik-external"
    service:
      externalIPs:
        - 10.132.246.2
