apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external-release
  namespace: traefik-external-system
spec:
  chart:
    spec:
      chart: traefik
      version: "37.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: traefik-external
  values:
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
      kubernetesIngress:
        allowExternalNameServices: true
    deployment:
      replicas: 2
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: "traefik-external"
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.132.246.2
