apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack-repository
  namespace: flux-system
spec:
  interval: 30m0s
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
