apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mariadb-operator.yaml
  - longhorn.yaml
  - prometheus.yaml
  - traefik.yaml
  - metallb.yaml
  - sealed-secrets.yaml
  - tailscale.yaml
  - reflector.yaml
  - jetstack.yaml
  - ot-container-kit.yaml
  - fossorial.yaml
  - kube-prometheus-stack.yaml
