apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ghost-ingress-route
  namespace: ghost-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cms.winetree94.com`)
      kind: Rule
      services:
        - name: ghost-service
          port: 80
  tls:
    secretName: letsencrypt-cert

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ghost-activity-pub-ingress-route
  namespace: ghost-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cms.winetree94.com`) && PathPrefix(`/.ghost/activitypub/`)
      kind: Rule
      priority: 1
      services:
        - name: ghost-activity-pub-external
          port: 443
          scheme: https
          passHostHeader: true
    - match: Host(`cms.winetree94.com`) && Path(`/.well-known/webfinger`)
      kind: Rule
      priority: 1
      services:
        - name: ghost-activity-pub-external
          port: 443
          scheme: https
          passHostHeader: true
    - match: Host(`cms.winetree94.com`) && Path(`/.well-known/nodeinfo`)
      kind: Rule
      priority: 1
      services:
        - name: ghost-activity-pub-external
          port: 443
          scheme: https
          passHostHeader: true
  tls:
    secretName: letsencrypt-cert
