apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ghost-ingress-route
  namespace: ghost-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cms.winetree94.com`)
      kind: Rule
      services:
        - name: ghost-service
          port: 80
  tls:
    secretName: letsencrypt-cert
