apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghost.namespace.yaml
  - ghost.database.secret.yaml
  - ghost.database.yaml
  - ghost.smtp.secret.yaml
  - ghost.deployment.yaml
  - ghost.service.yaml
  - ghost.ingress-route.yaml
