apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  # - ghost.yaml
  - joplin.yaml
  - authentik.yaml
  - openwebui.yaml
  - guacamole.yaml
  - nextcloud.yaml
  - davinci-resolve-project-server.yaml
  - proxies.yaml
