apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingress-route-http
  namespace: n8n-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`n8n.winetree94.com`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: n8n-service
          port: 5678
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingress-route
  namespace: n8n-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.winetree94.com`)
      kind: Rule
      services:
        - name: n8n-service
          port: 5678
  tls:
    secretName: letsencrypt-cert
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: n8n-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
