apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-deployment
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/kube-prometheus-stack
  prune: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-repositories
    - name: longhorn
