apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - pangolin.yaml
  - sealed-secrets.yaml
  - reflector.yaml
  - configs.yaml
  - longhorn.yaml
  - cert-manager.yaml
  - metallb.yaml
  - traefik.yaml
  - traefik-external.yaml
  - cloudnative-pg.yaml
  - mariadb-operator.yaml
  - ot-redis-operator.yaml
  - cloudflared.yaml
#  - kube-prometheus-stack.yaml
