apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: karakeep-ingress-route
  namespace: karakeep-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bookmarks.winetree94.com`)
      kind: Rule
      services:
        - name: karakeep-web-service
          port: 3000
  tls:
    secretName: letsencrypt-cert
