apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    email: admin@tinyrack.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tinyrack-homelab-letsencrypt
    solvers:
    - selector:
        dnsZones:
          - "tinyrack.net"
          - "winetree94.com"
          - "winetree94.click"
      dns01:
        cloudflare:
          email: winetree94@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api_token
