apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - davinci-resolve.namespace.yaml
  - davinci-resolve.database.superuser.secret.yaml
  - davinci-resolve.database.user.secret.yaml
  - davinci-resolve.database.yaml
