apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-release
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      version: "37.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: traefik
  values:
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
      kubernetesIngress:
        allowExternalNameServices: true
    deployment:
      replicas: 2
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: "traefik"
    service:
      annotations:
        metallb.io/loadBalancerIPs: 10.132.246.1

