apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nextcloud.namespace.yaml
  - nextcloud.database.superuser.secret.yaml
  - nextcloud.database.user.secret.yaml
  - nextcloud.database.yaml
  - nextcloud.redis.secret.yaml
  - nextcloud.redis.yaml
  - nextcloud.secret.yaml
  - nextcloud.helm-release.yaml
