apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - minio.proxy.yaml
  - router.proxy.yaml
  - garage.proxy.yaml
  - karakeep.proxy.yaml
  - docmost.proxy.yaml
  - openmediavault.proxy.yaml
