apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stalwart-http-ingress-route
  namespace: stalwart-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`mail.winetree94.com`)
      kind: Rule
      services:
        - name: stalwart-web-service
          port: 80
  tls:
    secretName: letsencrypt-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stalwart-https-ingress-route
  namespace: stalwart-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mail.winetree94.com`)
      kind: Rule
      services:
        - name: stalwart-web-service
          port: 443
  tls:
    secretName: letsencrypt-cert
