apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - forgejo.namespace.yaml
  - forgejo.database.superuser.secret.yaml
  - forgejo.database.user.secret.yaml
  - forgejo.database.yaml
#  - forgejo.helm-release.yaml

