apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-ip-pool
  interfaces:
    - enp6s0
  # nodeSelectors:
  #   - matchLabels:
  #       node-role.kubernetes.io/control-plane: ""