apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-release
  namespace: kube-prometheus-stack-system
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack-repository
    namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: kube-prometheus-stack
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotaions:
          kubernetes.io/ingress.class: traefik
        hosts:
          - grafana.intranet.winetree94.com
        tls:
          - secretName: letsencrypt-cert
            hosts:
              - grafana.intranet.winetree94.com
