{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      }
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgBlDv2BqSIf5vaWUI5D5702MoAGzTFTgFKtkZCB6ly4dT5JQYYy3EMXP075St+JANvfxOqLBZPpHzbc5HF8f0OOgEiK67vSP3wOoph9wNM9Wgz67Ov5h3d9F75Fd0eRxI3EgQLGyFuqP76OsMw0LUiKXUCcJ8WQ+t3vy7gSgoxzO7BWRwyEJJ8jPSo7cZdbVy8wGAXUnqrZmdGRhcaAd+GEiwcEsTe2yUerKEqp47WXEMOsC2ZEZvT2oH5mNpcIAQE7FmaNJSWkQlYjl+2RQUEVSdjLJOJCum3FnMG3GZLEbDlKTME5JOlVwnzM/bfATlhyoHZwOUSQvjUhfFeLyAQsiQ6sFnV8wa++0qGPb4dZr+87wqryZtExalHllao7QJI+lVUBexRzemv4xPZCD5jqLQF5Jqu9os+a0utbRXN5v/96jqV+iHMhDjIP7h83XYaf1jpC9ykCnvKOytzWFNAApLvhBYhKu0SLfBG2YcuVnMmJoXlN97Ljkt3HAd6PbV3GlkjTODUlz/1+MnJEJzV4IU+oJNyDkpTXhtNOekKbZI/lhWHlLntFJ9P7GFXG0QIRkzGf2mUtFf3o26tXNCoWDD1Kjhxv6jABp6bF6tCOt4nVuQ29Ohq2GGz3gORf236WorOB/4r0oU0TWXCH5Iux3V9ckSmxGkhv81XEGOc/B7ruhHUoba0K6h4SnOix9coRhCrSkwJFwtXUTsaLrjDCMVDDHg==",
      "AWS_ENDPOINTS": "AgAt8hRftBTAXdIIXKQ0X+Z2cqCoGPKDxgR5VPRDjSW/NwG2fkXz6s08BTUgtzAj+9pnvppOx7GyBoHzWSJapoNBfpfOzPjHOtt9ma7MBBMY+XW5DF8fMjmcOGe82Xm7xw5xRYeroFpFxsD/FeWzoL23b3Qo8f15lxzsbSja7WPMB7BNCX8oAkhrkfh4Nf/HvkAtSh/E7D1I+0pSJYXKw+TwG/D8vXedTV4Ny84P3hifCiQ09rSBBAWjlIrfuMJYPneiqL1W1sQxkvP3bJrIvPHOxpDszlttSNUOzEWmsTCt4EKBDHYSOarjQ0l7sJIkNh6V31KnpvIVvD6Eof0el3Hv9bUj2ImP5QzuI7Zc/+OolbAwU2Po+g2WqReycYHmy6aF8dIPFSJP+HykVaEKHZ5eiXi3+KXmviwvvhZxKHBv14JG1q7JwQM9GrVXVIccwk1A6mpcyQKlYRytgBUoE/VgPQO4eNcbfD+rpuUVyLs7W4f+IEui2NOpj899tNBdBenk+CDAorFpCVd8JB0nxygsFYD56J0s8QM4gph0NIQsvYmsZEVfenw6Cn8VzkGL+2AO+V0SAwtR6IPTcRA42T0jyLXeBo8K5GDWTF9sFr1riSMnJFB0ay4M3fkugEl9cBk3108djEZSwbHpt40qJqqAteFreGgAhPb7hPv3p/5qMTgOask/uf1+xpImd4FZc7VWNmhbCcHua1yc4s+Fm9Gls0aLUiDpBWzOU04=",
      "AWS_SECRET_ACCESS_KEY": "AgAKM7i5B06Msyj4k3tK2oeom/3pAOganhz09AwWulXx0LgvhQosRqHE0Qss8AOV9bE/RwoBWgPjijbgJle86cyr4v72vv5z7oGyLgTwlo1ZCNhWey2iPo3gad90NRZzPSZrft3cFVERihnFHq0fz7SAP3h/bkTpPqwA9d5+P6XntumfOunfTd8ykR416A4o3gMiJgC3MEz8UV8B/meIj62tUGXwoD+IX1t0Q17/Do1PG7OVZq5L2C1uqArHtaMlos0gw0/Epjd4SMLmemPvXwGdVfZ5H/c2oPg2Y31tuosjYUKroAw+qWffmRJbJyP71Ebi5tmyyE1jX9tuGEbnJ8CHyXtT2M8JKl3Nth6a68MI7x9ctU2UHc3V7QS5nL3VLfLnCh5hrEQ2Fd+SN0thJQe88b6zXKHWLs5C5otgtV9p95Jw9aB/l4gDbwMUA8PomHlIDt8JB/RqKD/E64OG4HVZuKjs4ieoZJJ/V6TxlT+JZhYQte+UV11DZFYhCZ33rlRGuC1+AEWzHUEHnmF7eTKHopMAhWo+9pg9bi00+E6exi+xkL/2yv4DPqwycGUtNi37vTYwIopQLhWjKxHKOV+O2ZCkwp8TAHY6y4hU7GG8qkHiPNkJmP6ZNMe+KIsapYrhFuTmPLb/MhgjlwJtY+QP5MA3adhzXnInfpUHbnf94bb9Sf1B7wSrBDwXBoL6HdHHlFus4pa5C9T3mP4h1yF0FLMzSJWLEQrb5S3/eroWDAVBmQkF5i/n"
    }
  }
}
