{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-homelab-s3-secret",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-homelab-s3-secret",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      }
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAK84Y7asCQnnFQn47oIeT6fREXyMFhsoyRFiecWGv/YFX4g8xOSaPfWONdH9eD9/VL0i5IBxxOwFCHVO4GZV2Em9hpPecC6PtVoo2zO9ObB7zKf7YtUDISvBqTlwfep9P9c3uTKMPgrMk9GNkXX4dcDtWv7VIg4jdEtwDW5yHDWYEBScIOhepNcbf5P0OE5rW9R5FFtaA4rTEnxl6txQDGxgBhpVIsUTmk/+aR58af5tbjVdxqKow69Kvu7m/llP1UUa1n5VRhlxgXRGkFOJLd4ot7pWKmqRch6eldIXLMJOXfeM5EEBax2MdN+VjRVyE2ifHYVZJDOTlMwoJLoHqhm9nKo+3JRA/llL/WYgcQ7DXC4lTafbfWckYleMpldp3+8TBr9dhhIUrYCrDxqS6HEgHMwBIzgz729i35/qULSstTO4Xe52DazcOHsy3MdgTBgVffzX1E8kQyU2dCNZhihBlQi2IIJ5nT1rUhAqkZcEw7rTTGoF4AYZzMKl6MrFxDggKTq/MrekFR34bKL/vorIIE4RoMc7LB9eQKS6AjMdC93Dnxeg99g0LUDfcVUT784s6pYts55RsB+0Rzz6H5XNYEI8ztg5Je0LBCXZwclV1vbXqkgtvWckuNL6D10bC88oFX9K//FdACN84xhpkxxoBZu1OrmT2uH0ntxlBLRvD+NZXW0OBFfqaKQ/jZ0lvIFW6C91xCrzd3QMHQ9pKaLjxGl1ARZwiwgQ==",
      "AWS_ENDPOINTS": "AgCV9Xm9iXToN2Gos1gQ8Yct48gwKRI0yDBKMi0PW/iugLz9Q7dwgxl5ijPeBdv+TlmKvWZjN7WqFEFRWt5EtwXp9x6X9zcNE0j3ojQZDtZwcG6sNR25LeI44DMwAamS9EKzRjLWZyA4tHypHke6zW4cVx0mIN2g8qdCRn3gGRQkPjdlTxk7HzGFpSyHJOTGjUjEGAPZaetimQ681NvWe+ehXyz6izciGqQhsxpoq18aZD4vczYKuw7yhN+O7k3hZOSAwmThKkxjeydE/K1FqUZ1d//+mtLEBE/zMkgz8MRPjHmUvV0V9oYrc0IJpFzj1Iur7RM2Ppweo2wU6ZoehmJqUX5PQwL4EctaGrZn53vrI/dq5yWo0ajI5/25uIIxsLvpORsqbmhy8Ph9YTeHnZjXs5EXFuB5j33/7wuyyqrYkTkCXxsOO7cxZuySlEv9j6NsXanzoTdvHdS/UZRYkuWys54aQq7ZSXNkF401Vbf+vM/+aTQpulr36Re/SVi044v/yjRFJv/nMuLRKH/XJJuLjuxJsBxnO8Y+/1PLjB/nV/nqrfKVbhbOCFQ6UQqTkaqOZdg3GP5v3z55YvYyUxvLClA/lnwDgLREibOOKeb8TqfCal3W9hoVBE7M2ecr7GNZUyNP6FRovvGklqWdYWUxtAkUdK2TeArL28rp/LXEISMSFoiJ8H0lO/3AGU60zdoCxUaLC/KCMT+UJSrVyBCOIdPVKEHH",
      "AWS_SECRET_ACCESS_KEY": "AgBmow7qlUASvn4ajAxO9cCwrA2dJOCjZaDrIW82ZYkVls1D2QsISkoc+5MJLXU+W0SgVVlkxgaiSLCoe7IJpnUuRu5W/s+3eo1bkpRWanvfK+JzR7W2KKI7RZhkzs8QSezfaHZ4bK8xsG7xehrmxe+6JeVS3AAGpQu8/7bkSoCtM5hMZ6vJSfCfmE34rGwL5dxDOZ4CFh4SpJnEFNI6DHaZQ7psJuYpAJ5YnYQSPhG2ylSIRpOsm2wb5BFClzKSCXNSTqmq1Wt+yGkYSZaXl4c1JZwMCbPvZSCC/uxpv7rBxTxmj6hIfnvaLtP8Hi2ggrsG37iO/mEFcKC1vHiFiLl04+tQvmsaO71aZmDQbWJ0L663N0XQh8Qtohqw81G7icsDwUA3WXfMc1YGSa8ONtnXDT7Wz1dRTX0e5uzfCVauNHVWcm+O928Wci4J+0mmKYlW+oiKjnCth13rmjC3XCBvs7lpYKDwNQ6EDFqntMxQ4iIZICWDNzmFVIX76Km8p5nHCagWwgasNyIwrCFVBxhKA9NHCuqCvhVICC7FYkzlYLymBK3SfmyJ0sE9aede47JE0MPjLs43GScw/ngmQmp+4RWoTcRtphu24MDPyl0siKUbl6SU/DdOMTVxCrS1MmmCpte9ODmYpG3Kyvc1vUNnOgxv3+yBhgTVg+PRgjz4Za20dFrmt/0BwRZJLSzMOJF7xiIIyrcgEs2COZfllydaI0lmqK1zwzucj7NS8POqako93rs5qfng5X8RE/bBhl8K0TdUZ8Uvs8uiquW6GPdt"
    }
  }
}
