apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: tailscale-pod-cidrs
  namespace: tailscale
spec:
  hostname: tinyrack-tailscale-connector
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "10.61.0.0/16"
      - "10.62.0.0/16"