apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openwebui.namespace.yaml
  - openwebui.database.superuser.secret.yaml
  - openwebui.database.user.secret.yaml
  - openwebui.database.yaml
  - openwebui.redis.secret.yaml
  - openwebui.redis.yaml
  - openwebui.secret.yaml
  - openwebui.oauth.secret.yaml
  - openwebui.helm-release.yaml
  - openwebui.ingress-route.yaml
