apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwebui-ingress-route
  namespace: openwebui-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ai.winetree94.com`)
      kind: Rule
      services:
        - name: open-webui
          port: 80
  tls:
    secretName: letsencrypt-cert
